https://pandas.pydata.org/

## Agenda
1. Pandas DataFrame
2. Pandas Series
3. Pandas Basic Operations

In [3]:
import pandas as pd
import numpy as np

#### Creating DataFrames

In [4]:
df = pd.DataFrame(np.arange(0, 20).reshape(5, 4), 
index=["Row 1", "Row 2", "Row 3", "Row 4", "Row 5"], 
columns=["Column 1", "Column 2", "Column 3", "Column 4",])

In [5]:
df

Column 1  Column 2  Column 3  Column 4
Row 1         0         1         2         3
Row 2         4         5         6         7
Row 3         8         9        10        11
Row 4        12        13        14        15
Row 5        16        17        18        19

In [6]:
type(df)

pandas.core.frame.DataFrame

In [7]:
df.head() # first 5 rows
df.head(2) # first 2 rows

Column 1  Column 2  Column 3  Column 4
Row 1         0         1         2         3
Row 2         4         5         6         7

In [8]:
df.tail() # last 5 rows

Column 1  Column 2  Column 3  Column 4
Row 1         0         1         2         3
Row 2         4         5         6         7
Row 3         8         9        10        11
Row 4        12        13        14        15
Row 5        16        17        18        19

In [9]:
df.describe() # describing data frame

Column 1   Column 2   Column 3   Column 4
count   5.000000   5.000000   5.000000   5.000000
mean    8.000000   9.000000  10.000000  11.000000
std     6.324555   6.324555   6.324555   6.324555
min     0.000000   1.000000   2.000000   3.000000
25%     4.000000   5.000000   6.000000   7.000000
50%     8.000000   9.000000  10.000000  11.000000
75%    12.000000  13.000000  14.000000  15.000000
max    16.000000  17.000000  18.000000  19.000000

In [10]:
df[["Column 1", "Column 2", "Column 3"]]

Column 1  Column 2  Column 3
Row 1         0         1         2
Row 2         4         5         6
Row 3         8         9        10
Row 4        12        13        14
Row 5        16        17        18

In [11]:
df[["Column 1"]]

Column 1
Row 1         0
Row 2         4
Row 3         8
Row 4        12
Row 5        16

In [23]:
type(df[["Column 1"]])

pandas.core.frame.DataFrame

In [24]:
df["Column 1"]

Row 1     0
Row 2     4
Row 3     8
Row 4    12
Row 5    16
Name: Column 1, dtype: int64

In [25]:
type(df["Column 1"])

pandas.core.series.Series

#### Difference between series and data frame

1. Series: When you work on only one column
2. DataFrame: When you work on more than one column, that's dataframe

In [28]:
df.loc[["Row 1", "Row 3"]]

Column 1  Column 2  Column 3  Column 4
Row 1         0         1         2         3
Row 3         8         9        10        11

In [29]:
type(df.loc[["Row 1", "Row 3"]])

pandas.core.frame.DataFrame

In [33]:
df.iloc[0:3, 0:2]

Column 1  Column 2
Row 1         0         1
Row 2         4         5
Row 3         8         9

In [34]:
df

Column 1  Column 2  Column 3  Column 4
Row 1         0         1         2         3
Row 2         4         5         6         7
Row 3         8         9        10        11
Row 4        12        13        14        15
Row 5        16        17        18        19

In [40]:
df.iloc[2:4, 1:3]

Column 2  Column 3
Row 3         9        10
Row 4        13        14

In [12]:
# converting a dataframe into an array
df.iloc[2:4, 1:3].values

array([[ 9, 10],
       [13, 14]])

In [13]:
# nan value: not a number / null value
np.nan

nan

In [17]:
df = pd.DataFrame([[1, np.nan, 2], [1, 3 ,4], [5, 4, 3]], 
index=["Row 1", "Row 2", "Row 3"], 
columns=["Column 1", "Column 2", "Column 3",])

df

Column 1  Column 2  Column 3
Row 1         1       NaN         2
Row 2         1       3.0         4
Row 3         5       4.0         3

In [21]:
df.isnull()

Column 1  Column 2  Column 3
Row 1     False      True     False
Row 2     False     False     False
Row 3     False     False     False

In [22]:
df.isnull().sum()

Column 1    0
Column 2    1
Column 3    0
dtype: int64

In [24]:
df.isna().sum()

Column 1    0
Column 2    1
Column 3    0
dtype: int64

In [25]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3 entries, Row 1 to Row 3
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Column 1  3 non-null      int64  
 1   Column 2  2 non-null      float64
 2   Column 3  3 non-null      int64  
dtypes: float64(1), int64(2)
memory usage: 96.0+ bytes


In [28]:
# value_counts can only be applied to a series
df["Column 1"].value_counts()

Column 1
1    2
5    1
Name: count, dtype: int64

In [36]:
df["Column 1"].unique() # array([1, 5])

array([1, 5])

In [35]:
df["Column 1"].nunique()

2

In [37]:
df = pd.DataFrame({'A': [1, 2, 3], 'B': [1, 1, 1]})

In [38]:
df

A  B
0  1  1
1  2  1
2  3  1

In [39]:
df['A'].unique()

array([1, 2, 3])

In [40]:
df['B'].unique()

array([1])

In [41]:
df['A'].nunique()

3

In [42]:
df['B'].nunique()

1

In [45]:
df.nunique(axis=0) # column wise unique values count

A    3
B    1
dtype: int64

In [46]:
df.nunique(axis=1) # row wise unique values count

0    1
1    2
2    2
dtype: int64

In [47]:
df = pd.DataFrame(np.arange(0, 20).reshape(5, 4), 
index=["Row 1", "Row 2", "Row 3", "Row 4", "Row 5"], 
columns=["Column 1", "Column 2", "Column 3", "Column 4",])

In [50]:
df

Column 1  Column 2  Column 3  Column 4
Row 1         0         1         2         3
Row 2         4         5         6         7
Row 3         8         9        10        11
Row 4        12        13        14        15
Row 5        16        17        18        19

In [54]:
df[df['Column 2']>5]

Column 1  Column 2  Column 3  Column 4
Row 3         8         9        10        11
Row 4        12        13        14        15
Row 5        16        17        18        19

In [65]:
df.to_csv('test.csv', index=False)

In [67]:
df1 = pd.read_csv('test.csv')
df1

Column 1  Column 2  Column 3  Column 4
0         0         1         2         3
1         4         5         6         7
2         8         9        10        11
3        12        13        14        15
4        16        17        18        19

In [73]:
df.to_excel('test.xlsx', index=False)

In [74]:
pd.read_excel('test.xlsx')

Column 1  Column 2  Column 3  Column 4
0         0         1         2         3
1         4         5         6         7
2         8         9        10        11
3        12        13        14        15
4        16        17        18        19

In [77]:
data = '{"employee_name": "Huzaifa", "email": "huzaifa.coder785@gmail.com", "job_profile": [{"title": "Team Lead", "role": "developer"}]}'

In [79]:
data

'{"employee_name": "Huzaifa", "email": "huzaifa.coder785@gmail.com", "job_profile": [{"title": "Team Lead", "role": "developer"}]}'

In [80]:
type(data)

str

In [81]:
pd.read_json(data)

employee_name                       email  \
0       Huzaifa  huzaifa.coder785@gmail.com   

                                   job_profile  
0  {'title': 'Team Lead', 'role': 'developer'}

In [82]:
df2 = pd.read_json(data)

In [83]:
df2['Salary'] = 100

In [84]:
df2

employee_name                       email  \
0       Huzaifa  huzaifa.coder785@gmail.com   

                                   job_profile  Salary  
0  {'title': 'Team Lead', 'role': 'developer'}     100

In [87]:
df2['job_profile']

0    {'title': 'Team Lead', 'role': 'developer'}
Name: job_profile, dtype: object

In [88]:
type(df2['job_profile'])

pandas.core.series.Series

In [91]:
dict(df2['job_profile'])

{0: {'title': 'Team Lead', 'role': 'developer'}}

In [94]:
dict(df2['job_profile'])[0]['title']

'Team Lead'

In [95]:
data

'{"employee_name": "Huzaifa", "email": "huzaifa.coder785@gmail.com", "job_profile": [{"title": "Team Lead", "role": "developer"}]}'

In [97]:
pd.read_json(data, orient="records") # default

employee_name                       email  \
0       Huzaifa  huzaifa.coder785@gmail.com   

                                   job_profile  
0  {'title': 'Team Lead', 'role': 'developer'}

In [100]:
pd.read_json(data, orient="index") # column name will become row index

0
employee_name                                        Huzaifa
email                             huzaifa.coder785@gmail.com
job_profile    [{'title': 'Team Lead', 'role': 'developer'}]

In [102]:
pd.read_json(data, orient="columns") 

employee_name                       email  \
0       Huzaifa  huzaifa.coder785@gmail.com   

                                   job_profile  
0  {'title': 'Team Lead', 'role': 'developer'}

In [103]:
df

Column 1  Column 2  Column 3  Column 4
Row 1         0         1         2         3
Row 2         4         5         6         7
Row 3         8         9        10        11
Row 4        12        13        14        15
Row 5        16        17        18        19

In [109]:
df.to_json()

'{"Column 1":{"Row 1":0,"Row 2":4,"Row 3":8,"Row 4":12,"Row 5":16},"Column 2":{"Row 1":1,"Row 2":5,"Row 3":9,"Row 4":13,"Row 5":17},"Column 3":{"Row 1":2,"Row 2":6,"Row 3":10,"Row 4":14,"Row 5":18},"Column 4":{"Row 1":3,"Row 2":7,"Row 3":11,"Row 4":15,"Row 5":19}}'

In [110]:
df.to_json(orient="records")

'[{"Column 1":0,"Column 2":1,"Column 3":2,"Column 4":3},{"Column 1":4,"Column 2":5,"Column 3":6,"Column 4":7},{"Column 1":8,"Column 2":9,"Column 3":10,"Column 4":11},{"Column 1":12,"Column 2":13,"Column 3":14,"Column 4":15},{"Column 1":16,"Column 2":17,"Column 3":18,"Column 4":19}]'

In [115]:
df2 = pd.read_csv("https://archive.ics.uci.edu/ml/machine-learning-databases/wine/wine.data", header=None)

In [116]:
df2.head()

0      1     2     3     4    5     6     7     8     9     10    11    12  \
0   1  14.23  1.71  2.43  15.6  127  2.80  3.06  0.28  2.29  5.64  1.04  3.92   
1   1  13.20  1.78  2.14  11.2  100  2.65  2.76  0.26  1.28  4.38  1.05  3.40   
2   1  13.16  2.36  2.67  18.6  101  2.80  3.24  0.30  2.81  5.68  1.03  3.17   
3   1  14.37  1.95  2.50  16.8  113  3.85  3.49  0.24  2.18  7.80  0.86  3.45   
4   1  13.24  2.59  2.87  21.0  118  2.80  2.69  0.39  1.82  4.32  1.04  2.93   

     13  
0  1065  
1  1050  
2  1185  
3  1480  
4   735

In [117]:
df2.to_json(orient="records")

'[{"0":1,"1":14.23,"2":1.71,"3":2.43,"4":15.6,"5":127,"6":2.8,"7":3.06,"8":0.28,"9":2.29,"10":5.64,"11":1.04,"12":3.92,"13":1065},{"0":1,"1":13.2,"2":1.78,"3":2.14,"4":11.2,"5":100,"6":2.65,"7":2.76,"8":0.26,"9":1.28,"10":4.38,"11":1.05,"12":3.4,"13":1050},{"0":1,"1":13.16,"2":2.36,"3":2.67,"4":18.6,"5":101,"6":2.8,"7":3.24,"8":0.3,"9":2.81,"10":5.68,"11":1.03,"12":3.17,"13":1185},{"0":1,"1":14.37,"2":1.95,"3":2.5,"4":16.8,"5":113,"6":3.85,"7":3.49,"8":0.24,"9":2.18,"10":7.8,"11":0.86,"12":3.45,"13":1480},{"0":1,"1":13.24,"2":2.59,"3":2.87,"4":21.0,"5":118,"6":2.8,"7":2.69,"8":0.39,"9":1.82,"10":4.32,"11":1.04,"12":2.93,"13":735},{"0":1,"1":14.2,"2":1.76,"3":2.45,"4":15.2,"5":112,"6":3.27,"7":3.39,"8":0.34,"9":1.97,"10":6.75,"11":1.05,"12":2.85,"13":1450},{"0":1,"1":14.39,"2":1.87,"3":2.45,"4":14.6,"5":96,"6":2.5,"7":2.52,"8":0.3,"9":1.98,"10":5.25,"11":1.02,"12":3.58,"13":1290},{"0":1,"1":14.06,"2":2.15,"3":2.61,"4":17.6,"5":121,"6":2.6,"7":2.51,"8":0.31,"9":1.25,"10":5.05,"11":1.06,"