In [2]:
import numpy as np

In [4]:
# converting a list into array
lst = [1, 2, 3, 4]
arr = np.array(lst)

In [5]:
type(arr)

numpy.ndarray

In [7]:
arr.shape
# our array "arr" is an one-dimensional array

(4,)

In [11]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]]) # nested list
print(arr1)

[[1 2 3]
 [4 5 6]]


In [10]:
arr1.shape
# our array "arr1" is a two-dimensional array with 2 rows and three columns

(2, 3)

In [12]:
# changing the shape of "arr1"
arr1.reshape(3,2) # it means 3 rows and 2 columns

array([[1, 2],
       [3, 4],
       [5, 6]])

In [16]:
# difference between one-dimensional and two-dimensional
print("one-dimensional", arr) # 1 opening and closing square brackets
print("---------")
print("two-dimensional\n", arr1) # 2 opening and closing square brackets (nested)
# you can see the difference below

one-dimensional [1 2 3 4]
---------
two-dimensional
 [[1 2 3]
 [4 5 6]]


In [17]:
# changing tuple to array
np.array((1, 2, 3, 4))

array([1, 2, 3, 4])

In [18]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [20]:
# checking data type of our elements
arr1.dtype

dtype('int64')

In [30]:
# creating array with the help of arange function
print(np.arange(1, 10, 2), end="\n\n") # start end step
print(np.arange(1, 10, 2).shape, end="\n\n")
print(np.arange(1, 10, 2).reshape(5, 1), end="\n\n")
print(np.arange(1, 10, 2).reshape(5, 1).shape, end="\n\n")

# the arange funciton is somewhat similar to range function we saw before

[1 3 5 7 9]

(5,)

[[1]
 [3]
 [5]
 [7]
 [9]]

(5, 1)



In [34]:
# maybe an interview question

# Q. quickly create an array in reverse order
np.arange(50, 1, -2)

array([50, 48, 46, 44, 42, 40, 38, 36, 34, 32, 30, 28, 26, 24, 22, 20, 18,
       16, 14, 12, 10,  8,  6,  4,  2])

In [37]:
# equally spaced elements
np.linspace(1, 20, 40) # linearly spaced, 40 elements between 1 to 20 equally, i.e. 40 equally spaced elements
np.linspace(1, 20, 40).shape
np.linspace(1, 20, 40).reshape(20 ,2)

array([[ 1.        ,  1.48717949],
       [ 1.97435897,  2.46153846],
       [ 2.94871795,  3.43589744],
       [ 3.92307692,  4.41025641],
       [ 4.8974359 ,  5.38461538],
       [ 5.87179487,  6.35897436],
       [ 6.84615385,  7.33333333],
       [ 7.82051282,  8.30769231],
       [ 8.79487179,  9.28205128],
       [ 9.76923077, 10.25641026],
       [10.74358974, 11.23076923],
       [11.71794872, 12.20512821],
       [12.69230769, 13.17948718],
       [13.66666667, 14.15384615],
       [14.64102564, 15.12820513],
       [15.61538462, 16.1025641 ],
       [16.58974359, 17.07692308],
       [17.56410256, 18.05128205],
       [18.53846154, 19.02564103],
       [19.51282051, 20.        ]])

In [44]:
# generating zeros
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [47]:
np.ones((5, 2, 8)) # three dimesnional. 2, 3 represets inner arrays. 5 represents the outer array
5 + np.ones((5, 2)) # broadcasting operation

array([[6., 6.],
       [6., 6.],
       [6., 6.],
       [6., 6.],
       [6., 6.]])

In [54]:
# creating an identity matrix
np.eye(4)
np.eye(4).reshape(8, 2)

# alternative
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [57]:
# generating random numbers
print("Genrating random numbers (Uniform Distribution) - Values ranging between 0 to 1")
np.random.rand(2, 3)

Genrating random numbers (Uniform Distribution) - Values ranging between 0 to 1


array([[0.6753143 , 0.78008707, 0.43344389],
       [0.36206553, 0.84785274, 0.61951147]])

In [60]:
# generating random numbers in normal distribution
print("Genrating random numbers (Normal Distribution) - with meand = 0 and sd = 1")
np.random.randn(5, 3)

Genrating random numbers (Normal Distribution) - with meand = 0 and sd = 1


array([[ 3.60756502e-01, -1.79471620e+00, -1.10901848e+00],
       [ 1.20558701e+00,  9.66552148e-02, -1.13316559e+00],
       [ 1.19953132e-01,  2.21089484e+00, -9.79120905e-04],
       [ 2.27406704e-01,  6.96560869e-02, -1.12870878e+00],
       [-8.94362440e-01,  2.05976195e-01,  5.04857281e-01]])

In [92]:
np.random.randint(1, 100)
np.random.randint(1, 100, 50)
np.random.randint(1, 100, (4, 4))

array([[78,  4, 94, 43],
       [46, 24, 62, 77],
       [62, 48, 73, 35],
       [86, 65, 85, 75]])

In [ ]:
# krish sir words

'''
never get jealous, when you do all things correctly, believe that every good thing will happen to you, 
no matter what anybody does to you, be happy, stay calm, you do the righ thing! u know in your inner self,
that where u need to improve, if someone says that there's some bad in you, take it, and improve yourself!
'''

In [97]:
arr = np.arange(0, 11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [104]:
# Slicing
arr[2:7] # array([2, 3, 4, 5, 6])
arr[2] # 2

# Slicing from backward
arr[-1] # 10
arr[-1:7] # array([], dtype=int64)
arr[-1:7:-1] # array([10,  9,  8]) | by default ":-1" this value is 1
arr[-1:3:-1] # array([10,  9,  8,  7,  6,  5,  4])
arr[-1:3:-2] # array([10,  8,  6,  4])

array([10,  8,  6,  4])

In [18]:
# Slicing with 2-dimensional array
arr1 = np.random.randint(2, 100, 20).reshape(5, 4)

# pick 3 rows and all columns
arr1[0:3]

# pick 3 rows and 3 columns
arr1[0:3, 0:3]

# pick last 2 rows and last 3 columns from those rows
arr1[3:, 1:4] # before comman, row slicing || after comma, column slicing

# pick 3rd and 4th row and middle 2 columns from those rows
arr1[2:4, 1:3]

# pick 3rd and 4th row and 1st and last columns from those rows
arr1[2:4, 1:5:2]

array([[92, 45],
       [28, 38]])

In [19]:
# universal functions
arr1 = np.random.randint(1, 100, (3, 3))
arr2 = np.random.randint(20, 100, (3, 3))

In [20]:
arr1

array([[19, 62, 19],
       [10, 87, 15],
       [82, 11, 18]])

In [21]:
arr2

array([[38, 82, 68],
       [86, 54, 55],
       [84, 79, 49]])

In [23]:
arr1 + arr2 # shape should be same of both arrays for calculations

array([[ 57, 144,  87],
       [ 96, 141,  70],
       [166,  90,  67]])

In [24]:
arr1 - arr2

array([[-19, -20, -49],
       [-76,  33, -40],
       [ -2, -68, -31]])

In [25]:
arr1 * arr2

array([[ 722, 5084, 1292],
       [ 860, 4698,  825],
       [6888,  869,  882]])

In [26]:
arr1 / arr2

array([[0.5       , 0.75609756, 0.27941176],
       [0.11627907, 1.61111111, 0.27272727],
       [0.97619048, 0.13924051, 0.36734694]])

In [27]:
np.sqrt(arr1)

array([[4.35889894, 7.87400787, 4.35889894],
       [3.16227766, 9.32737905, 3.87298335],
       [9.05538514, 3.31662479, 4.24264069]])

In [28]:
np.exp(arr2)

array([[3.18559318e+16, 4.09399696e+35, 3.40427605e+29],
       [2.23524660e+37, 2.83075330e+23, 7.69478527e+23],
       [3.02507732e+36, 2.03828107e+34, 1.90734657e+21]])

In [29]:
np.log10(arr1)

array([[1.2787536 , 1.79239169, 1.2787536 ],
       [1.        , 1.93951925, 1.17609126],
       [1.91381385, 1.04139269, 1.25527251]])

In [30]:
arr1 = np.arange(1, 10)

In [31]:
arr1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
arr1[2:] = 1000 # broadcasting operation

In [35]:
arr1

array([   1,    2, 1000, 1000, 1000, 1000, 1000, 1000, 1000])

In [38]:
arr1 = np.random.randint(1, 100, (3, 3))
arr2 = np.random.randint(20, 100, (3, 3))

In [37]:
np.dot(arr1, arr2)

array([[11926, 15092, 16009],
       [ 6822, 11132, 10765],
       [ 8438, 10292, 10966]])

In [39]:
np.matmul(arr1, arr2)

array([[4708, 5262, 5608],
       [6618, 8530, 7668],
       [7495, 7041, 8814]])